import { makeStyles, Theme, createStyles } from '@material-ui/core/styles'

export const useStyles = makeStyles((theme: Theme) =>
  createStyles({
    textCenter: {
      background: '#f6f6f6',
    },
    mainContent: {
      backgroundColor: '#090909',
      display: 'flex',
      justifyContent: 'center',
    },
    contentGridText: {
      marginTop: 'auto',
      marginBottom: 'auto',
      marginRight: '20px',
      marginLeft: '30px',
    },
    contentGridImg: {
      padding: '50px 30px',
    },
    contentDescImg: {
      borderRadius: '50px',
      border: 'solid 5px #222222',
      minHeight: '360px',
      background: 'url(../img/landing/philosopydesc.jpg) center no-repeat',
      backgroundSize: 'cover',
    },
    contentImg: {
      borderRadius: '50px',
      border: 'solid 5px #222222',
      minHeight: '360px',
      background: 'url(../img/landing/philosophy.jpg) center no-repeat',
      backgroundSize: 'cover',
    },
    svgMainUp: {
      backgroundColor: '#090909',
    },
    pathStyleUp: {
      stroke: '#f6f6f6',
      fill: '#f6f6f6',
    },
    svgMainDown: {
      backgroundColor: '#f6f6f6',
    },
    pathStyleDown: {
      stroke: '#090909',
      fill: '#090909',
    },
    contentTextTitle: {
      color: '#ffffff',
      fontFamily: "'Spartan', Sans-serif",
      fontSize: '50px',
      textAlign: 'left',
      fontWeight: 600,
      letterSpacing: '2px',
      marginBottom: '20px',
    },
    contentTextContext1: {
      textAlign: 'justify',
      color: '#999999',
      fontSize: '16px',
      marginBottom: '20px',
    },
    contentTextContext2: {
      color: '#ffffff',
      textAlign: 'left',
      fontFamily: "'ZCOOL XiaoWei', Sans-serif",
      fontSize: '30px',
      fontWeight: 400,
      marginBottom: '20px',
    },
    philosophyOptions: {
      padding: '80px 50px',
    },
    philosophyOptionsBtn: {
      border: '1px solid #d5d5d5',
      borderRadius: '20px',
      backgroundColor: '#ffffff',
      textAlign: 'center',
    },
    philosophyOptionsBtnItem: {
      color: 'black',
      fontWeight: 600,
      whiteSpace: 'nowrap',
      padding: '25px 15px',
      fontSize: '16px',
      fontFamily: "'Spartan', sans-serif",
    },
    philosophyOptionsBtnItemActive: {
      fontSize: '16px',
      fontFamily: "'Spartan', sans-serif",
      overflow: 'auto',
      fontWeight: 600,
      color: '#5a8cdd',
      height: 'calc(80% - 2px)',
      width: '100%',
      transform: 'translatex(0%) translatey(10px)',
      backgroundColor: '#fff',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: '50px',
      border: '1px solid #5a8cdd',
      boxShadow: '5px 5px 15px #5a8cdd70',
      zIndex: 10,
    },
    philosophyOptionsBtnGrid: {},
    philosophyOptionsBtnGridActive: {
      transform: 'translatex(0%) translatey(-20px)',
      paddingLeft: '10px',
      paddingRight: '10px',
      borderTop: '2px solid #d5d5d5',
      borderRadius: '40px',
      background: 'white',
      display: 'flex',
      justifyContent: 'center',
      marginTop: '-2px',
    },
    philosophyOptionsContent: {
      margin: '50px 0px 0px 0px',
      padding: '2.1875em 1.375em',
      borderRadius: '10px 10px 10px 10px',
      overflow: 'hidden',
      boxShadow: '0px 0px 35px 0px rgb(149 174 215 / 46%)',
      borderStyle: 'solid',
      borderWidth: '0px 0px 0px 0px',
      backgroundColor: '#ffffff',
      fontSize: '16px',
      fontFamily: "'Spartan', sans-serif",
      fontWeight: 500,
      textAlign: 'left',
      color: 'black',
    },
  }),
)
